Feature/reset password
sosinc/sos-app pull request #45
Opened 2020-06-15 08:43 UTC by kajalelohai

wip: sent otp for reset password

2020-06-15 12:44 UTC, bitspook requested changes

2020-06-15 12:44 UTC, channikhabra commented on ui/src/duck/auth.ts
> +  { rejectValue: Error; state: PasswordResetOTP }
`createAsyncThunk` gets the state of the slice. So here it should be `AuthState` and not `PasswordResetOTP`.

2020-06-15 12:44 UTC, channikhabra commented on ui/src/entities/User.ts
> +  return data ? data.sendPasswordResetOtp : undefined;
We don't need to check for absence of `data` this way. We can use [optional-chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) feature of typescript.

2020-06-15 12:44 UTC, channikhabra commented on ui/src/entities/User.ts
> +export const sendPasswordResetOTP = async (payload: SendOTPPayload): Promise<undefined> => {
We don't need to create a new interface for accepting arguments of this function. It is (and will quite likely always be) a single string. We can save ourselves some boilerplate by making it `async (email: string)` instead. 

```suggestion
export const sendPasswordResetOTP = async (email: string): Promise<undefined> => {
```

2020-06-16 06:37 UTC, jkhabra approved these changes

2020-06-21 05:05 UTC, jkhabra approved these changes

2020-06-21 05:05 UTC, bitspook approved these changes

2020-06-21 05:06 UTC, merged